name: "Jacky Ho"
description: "A data scientist"

url: 'https://jackyho112.github.io/jackyho112-2.github.io/'
baseurl: 'https://jackyho112.github.io/jackyho112-2.github.io/'

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
paginate: 10
paginate_path: /page-:num

#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/
